services:
  - type: worker
    name: govspark-discord-recorder
    runtime: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_APPLICATION_ID
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: RECORDING_RESULT_CHANNEL_NAME
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
